version: "3"

services: 
    app: 
        build: .
        command: npm run start:webapp
        ports: 
            - "8080:8080"
        volumes: 
            - .:/home/node/app
    proxy:
        build: .
        command: node proxy.js
        ports:
            - "8081:8081"
        volumes: 
            - .:/home/node/app