version: "3.8"

services: 
    proxy:
        build: proxy
        command: node proxy.js
        image: sapui5onlineshop.azurecr.io/proxy-server
        container_name: proxy-server
        ports:
            - "6397:6397"
        volumes: 
            - .:/home/node/app
    app: 
        build: .
        image: sapui5onlineshop.azurecr.io/shop-app
        command: npm run start:webapp
        container_name: shop-app
        ports: 
            - "80:80"
        volumes: 
            - .:/home/node/app